language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
env:
  global:
    secure: LGSZXFJX81z73SZcoQ8OBzLjMi7geUhcUyH5WyDOcyrGZSwufrMw79puzbIvv08jj9bqYc1vviFdAl4kgTGLAjxZCsqKFqYSn3Iw2kuZ+hjS/GErR1TxPPW9epwkBp0EllLdrg7ygzX3DgTB5LASh1Qmd9McnPFoSdwasRJwCSyvwT4p1csYqmOsV2X2Uv1zpmwv4bOSRMeR5Kjyscc1d0josquVC/MmwZ+APa1GhFri/ozKIWgzgMAPafkpIsCwUni7Y8Wz7DdDu2EW/qCs0yvan9r8F10d0nNlDMQ5vSi7OjGqAo+/G5ImkAFXdAJCoBgslTS0If7CUKq/BQRxBsiO+dEJMT/WInXJ24DjZ6AlzTuySKlgXaGnV0hY6KBYxgoGrlEaic/qWZlkywA7MsfhCsgbVFsUzggIHtiWvyjKXx7/ixfnPQqua+dTcKtJl+Cygtj6af6icmijmy1u2/ahJJCrLMjsjOqgk0duorq5zZaJO2tIwrLB2/HA49EHiHtq65PgZvRAO1YNNKZ9vEC4ghLOPvP9K/B1KZks++dIqhFq5voNJtJRwuYqVQUswjAK2fMHz58YKGVJYARftQxDCo2uiaqJfdu22knvtSypTUbR99/kFZA/10tgg2evvjwQcjuuloCxnrK+5Z94mZapxKAYxcWF6zxggowLVBk=
addons:
  sonarcloud:
    organization: dotwebstack
    token:
      secure: HSdBT8AaylyTtZHq73L98HmMXvuUQ7exj4/ApZnu6z1k5q7mymphDjOuMrXkWL4Tp6+2HAXpqlKnckrjx2G7h/3O5N/hf1FQMrnbQK8jGeKtG8X0yuRg/H2CZwv4aVORlrvpt86FnwivuC3TaOhcecbcs5b/f1kORn6aSmyV6KAV1rV6uNzZPHXNdcC+YK98RpTHxzh2kjW9/IHMByn14Jli27/GLW4ks5Uc7oyC1vGSIHuEqAcGPPoXVUxsfOYEakPsdyKHCk71HQ1OdukZahkNnjdSOaJNKjBJFlcgg4umYUuRD4cRVV9rDSOqwuYGwktpU7tLveggM9Ihyv/WEuOmplms8pjZH5aY6FI8/UHh83tybQfSfyE+HAMnJIyVZ6iVLEh2GDGfd45WRmqR25BSsKhU/F45nyahVzEP3jMZQ9fXOg4cYzEbdD8Df3zOjw6Q4vUqno7MbieH3QEDYuX++4GrzILFwSX6j+4zIRGayZyZRrQuQw1GSvf9ro+T2G9B5XS4xJcDFQ2GJ7+CgVHwBjC+e9zGkzv6ipx8oI1BO3vcaX7vWvgtUGhzlvMArPdZAvGfM89XkGKpShMFqZvrJXlCqqHiWF4J4f9Qtly6//Er5Rf3vSC53BJUIvd+R1BeVg3/Ynb/blwLJHRTwiKsqHrwJOGH+DdC3+Scois=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
deploy:
  - provider: script
    script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy
    skip_cleanup: true
    on:
      branch: master
