language: java
jdk:
  - oraclejdk8
env:
  global:
    secure: Av2mpl9zx5M/DVjBFpLSPABmMh9nhfzZ5VEt0+cp807N+pHNBC0l9TgIKvEygrzSmw6+u4hxY1Mh4MsqeOwCy6P1Lq+GGZApfbA8d80mPH3jG+Po4h9G+5K6P+illYV0qckJXjpyJ3FfEB5Jraoimx8pEwrQkMyrnQiF1+dijFWOPR4FYvCjWuMV0FnhycEWoCoEjbLHXvkRCcAWcA8E1wPzbh8RmUnhS3jmaS0rtpoFubzdtwvo65VEFy133+61SUSX4UPWCLm3V5jNVaQ/jC8AntdCq5ZMKFAN9qtq1kFpZ0ga2egd4PmXiMKcfT+cnoLcha7LM1hMVcfZbIVCsw1bOHiQXOsj7Q2R8DDgyXF7eFvDWPLsNtbmd4i8R8vhIKB6j3x0UnmxEyl7kG1I473LAinw3K2rN43YtNnYjHkDnMbOosmG6DoEHv+PRKjy4lMQlkDR7uXAXuZocnPBLhE/uzdnWZoJKbWdjVkrCC6Vvx7Q4Sr74nbvZml7cbt69UIvXNdYcCVyyRWbTtFR8eIqrf01Z0LWVfc0ZQE/eUnARUq+qy0OXR/1weUbf1hc35MQ6lKUbXDoWbhAPh9Qnr51CsfXJ20nOBzUI71TgfN+NhxDKZmtsJ8w9jThx/Qjf3Uex7JHbV+c7XcBuqCmQJSLzLjbGaqeqFNZkpdiyVA=
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
addons:
  sonarcloud:
    organization: dotwebstack
    token:
      secure: HSdBT8AaylyTtZHq73L98HmMXvuUQ7exj4/ApZnu6z1k5q7mymphDjOuMrXkWL4Tp6+2HAXpqlKnckrjx2G7h/3O5N/hf1FQMrnbQK8jGeKtG8X0yuRg/H2CZwv4aVORlrvpt86FnwivuC3TaOhcecbcs5b/f1kORn6aSmyV6KAV1rV6uNzZPHXNdcC+YK98RpTHxzh2kjW9/IHMByn14Jli27/GLW4ks5Uc7oyC1vGSIHuEqAcGPPoXVUxsfOYEakPsdyKHCk71HQ1OdukZahkNnjdSOaJNKjBJFlcgg4umYUuRD4cRVV9rDSOqwuYGwktpU7tLveggM9Ihyv/WEuOmplms8pjZH5aY6FI8/UHh83tybQfSfyE+HAMnJIyVZ6iVLEh2GDGfd45WRmqR25BSsKhU/F45nyahVzEP3jMZQ9fXOg4cYzEbdD8Df3zOjw6Q4vUqno7MbieH3QEDYuX++4GrzILFwSX6j+4zIRGayZyZRrQuQw1GSvf9ro+T2G9B5XS4xJcDFQ2GJ7+CgVHwBjC+e9zGkzv6ipx8oI1BO3vcaX7vWvgtUGhzlvMArPdZAvGfM89XkGKpShMFqZvrJXlCqqHiWF4J4f9Qtly6//Er5Rf3vSC53BJUIvd+R1BeVg3/Ynb/blwLJHRTwiKsqHrwJOGH+DdC3+Scois=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
deploy:
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
      branch: master
